---

- hosts: all
  become: true
  tasks:
    - name: Update cache -  apt update 
      apt:
        update-cache: true

    - name: install apache2 package
      apt:
        name: apache2
        state: latest

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
        state: latest
    
