---

- hosts: all
  become: true
  tasks:
    - name: Update cache -  apt update 
      apt:
        update-cache: true

    - name: remove apache2 package
      apt:
        name: apache2
        state: absent

    - name: remove php support for apache2
      apt:
        name: libapache2-mod-php
        state: absent
    
